import type { CommandPreset, FormField } from "../../types/command";

// 辅助函数：创建标准的单输入文件字段
const createInput = (maxSizeMB = 500): FormField => ({
	name: "input",
	label: "输入文件",
	type: "file-input",
	accept: "video/*",
	multiple: false,
	maxSizeMB,
	description: "选择要处理的视频文件",
	required: true,
});

// 辅助函数：创建标准的输出文件字段
const createOutput = (ext = "mp4", mimeType?: string): FormField => ({
	name: "output",
	label: "输出文件名",
	type: "file-output",
	defaultValue: `output.${ext}`,
	defaultExtension: ext,
	mimeType,
	description: "输出文件的名称",
	required: true,
});

/**
 * 默认预设命令
 *
 * 注意：这些预设已经过筛选，确保与 WebAssembly 兼容
 * - 移除了不支持的编解码器和格式
 * - 优化了内存使用
 * - 使用动态参数提高灵活性
 */
export const defaultPresets: Omit<
	CommandPreset,
	"id" | "createdAt" | "updatedAt"
>[] = [
	{
		name: "复制流（不重新编码）",
		description: "快速复制视频和音频流，不进行重新编码，速度最快",
		category: "基础操作",
		ffmpegArgs: ["-i", "{{input}}", "-c", "copy", "{{output}}"],
		requiresReencode: false,
		estimatedMemoryMB: 50,
		formSchema: [createInput(500), createOutput("mp4")],
	},
	{
		name: "转换为 WebM",
		description:
			"使用 VP9 和 Opus 编码器转换为 WebM 格式（⚠️ 大文件或高分辨率视频可能极慢）",
		category: "格式转换",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-c:v",
			"libvpx-vp9",
			"-b:v",
			"1M",
			"-crf",
			"32",
			"-speed",
			"8",
			"-threads",
			"4",
			"-c:a",
			"libopus",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 250,
		formSchema: [
			createInput(100), // 限制为 100MB，VP9 编码很慢
			createOutput("webm", "video/webm"),
		],
	},
	{
		name: "提取音频为 MP3",
		description: "从视频中提取音频轨道并转换为 MP3 格式",
		category: "音频处理",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-vn",
			"-acodec",
			"libmp3lame",
			"-q:a",
			"2",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 150,
		formSchema: [createInput(300), createOutput("mp3", "audio/mpeg")],
	},
	{
		name: "视频缩放",
		description: "调整视频分辨率（支持自定义宽度和高度）",
		category: "视频处理",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-vf",
			"scale={{width}}:{{height}}",
			"-b:v",
			"{{bitrate}}k",
			"-crf",
			"{{quality}}",
			"-c:a",
			"copy",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 300,
		formSchema: [
			createInput(200),
			{
				name: "width",
				label: "宽度（像素）",
				type: "number",
				defaultValue: 1280,
				min: 128,
				max: 3840,
				step: 2,
				required: true,
				description: "输出视频的宽度（必须是偶数）",
			},
			{
				name: "height",
				label: "高度（像素）",
				type: "number",
				defaultValue: 720,
				min: 128,
				max: 2160,
				step: 2,
				required: true,
				description: "输出视频的高度（必须是偶数）",
			},
			{
				name: "bitrate",
				label: "视频码率（kbps）",
				type: "slider",
				defaultValue: 2000,
				min: 500,
				max: 10000,
				step: 100,
				description: "视频比特率，值越高质量越好但文件越大",
			},
			{
				name: "quality",
				label: "CRF 质量",
				type: "slider",
				defaultValue: 23,
				min: 18,
				max: 35,
				step: 1,
				description: "CRF 值：18=最高质量，28=平衡，35=最低质量",
			},
			createOutput("mp4"),
		],
	},
	{
		name: "转换为 WebM（快速）",
		description: "使用 H.264 转 WebM 容器（不重新编码视频，速度快）",
		category: "格式转换",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-c:v",
			"copy",
			"-c:a",
			"libopus",
			"{{output}}",
		],
		requiresReencode: false,
		estimatedMemoryMB: 100,
		formSchema: [createInput(300), createOutput("webm", "video/webm")],
	},
	{
		name: "提取视频片段",
		description: "提取视频片段（可自定义起始时间和时长）",
		category: "视频处理",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-ss",
			"{{startTime}}",
			"-t",
			"{{duration}}",
			"-c",
			"copy",
			"{{output}}",
		],
		requiresReencode: false,
		estimatedMemoryMB: 50,
		formSchema: [
			createInput(500),
			{
				name: "startTime",
				label: "起始时间",
				type: "text",
				defaultValue: "00:00:10",
				placeholder: "HH:MM:SS",
				required: true,
				description: "起始时间点（格式：HH:MM:SS）",
			},
			{
				name: "duration",
				label: "持续时长",
				type: "text",
				defaultValue: "00:00:05",
				placeholder: "HH:MM:SS",
				required: true,
				description: "提取的时长（格式：HH:MM:SS）",
			},
			createOutput("mp4"),
		],
	},
	{
		name: "转换为 GIF",
		description: "将视频转换为 GIF 动图（可自定义帧率和宽度）",
		category: "格式转换",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-vf",
			"fps={{fps}},scale={{width}}:-1:flags=lanczos",
			"-c:v",
			"gif",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 200,
		formSchema: [
			createInput(100),
			{
				name: "fps",
				label: "帧率（FPS）",
				type: "slider",
				defaultValue: 10,
				min: 5,
				max: 30,
				step: 1,
				description: "每秒帧数，值越高越流畅但文件越大",
			},
			{
				name: "width",
				label: "宽度（像素）",
				type: "number",
				defaultValue: 320,
				min: 160,
				max: 1920,
				step: 10,
				required: true,
				description: "输出 GIF 的宽度（高度自动计算）",
			},
			createOutput("gif", "image/gif"),
		],
	},
	{
		name: "压缩视频",
		description: "使用 H.264 编码器压缩视频（可自定义 CRF 和音频码率）",
		category: "视频处理",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-c:v",
			"libx264",
			"-crf",
			"{{crf}}",
			"-c:a",
			"aac",
			"-b:a",
			"{{audioBitrate}}k",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 250,
		formSchema: [
			createInput(200),
			{
				name: "crf",
				label: "CRF 质量",
				type: "slider",
				defaultValue: 28,
				min: 18,
				max: 35,
				step: 1,
				description: "CRF 值越大压缩越多（18=最高质量，35=最低质量）",
			},
			{
				name: "audioBitrate",
				label: "音频码率（kbps）",
				type: "slider",
				defaultValue: 128,
				min: 64,
				max: 320,
				step: 32,
				description: "音频比特率",
			},
			createOutput("mp4"),
		],
	},
	{
		name: "合并视频",
		description: "按顺序合并两个视频文件",
		category: "视频处理",
		ffmpegArgs: [
			"-i",
			"{{input1}}",
			"-i",
			"{{input2}}",
			"-filter_complex",
			"[0:v][0:a][1:v][1:a]concat=n=2:v=1:a=1[v][a]",
			"-map",
			"[v]",
			"-map",
			"[a]",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 350,
		formSchema: [
			{
				name: "input1",
				label: "第一个视频",
				type: "file-input",
				accept: "video/*",
				multiple: false,
				maxSizeMB: 150,
				description: "选择第一个要合并的视频",
				required: true,
			},
			{
				name: "input2",
				label: "第二个视频",
				type: "file-input",
				accept: "video/*",
				multiple: false,
				maxSizeMB: 150,
				description: "选择第二个要合并的视频",
				required: true,
			},
			createOutput("mp4"),
		],
	},
	{
		name: "旋转视频",
		description: "旋转视频（支持多种旋转方向）",
		category: "视频处理",
		ffmpegArgs: [
			"-i",
			"{{input}}",
			"-vf",
			"transpose={{direction}}",
			"-c:a",
			"copy",
			"{{output}}",
		],
		requiresReencode: true,
		estimatedMemoryMB: 250,
		formSchema: [
			createInput(200),
			{
				name: "direction",
				label: "旋转方向",
				type: "select",
				defaultValue: "1",
				required: true,
				description: "选择视频旋转的方向",
				options: [
					{ label: "顺时针旋转 90°", value: "1" },
					{ label: "逆时针旋转 90°", value: "2" },
					{ label: "顺时针旋转 90° + 垂直翻转", value: "3" },
					{ label: "逆时针旋转 90° + 垂直翻转", value: "0" },
				],
			},
			createOutput("mp4"),
		],
	},
];
